import type { Metadata } from "next";
import { Poppins } from "next/font/google";
// import { LocomotiveScrollProvider } from "react-locomotive-scroll";

import "./globals.css";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${poppins.className} antialiased`}>{children}</body>
    </html>
  );
}
